language: go
sudo: required
before_install:
    - sudo apt-get update
    - sudo apt-get install gdisk
script:
    - git clone https://github.com/coreos/ignition
    - sudo -E $(which go) run volume_create.go
