language: go
sudo: required
dist: trusty
addons:
  apt:
    packages:
    # install cross compilers for cgo support.
    - gcc-aarch64-linux-gnu
    - libc6-dev-arm64-cross
    - libblkid-dev
    - kpartx
    - gdisk
script:
    - git clone https://github.com/coreos/ignition /root/ignition
    - sudo 'cd /root/ignition; ./build'
    - sudo -E $(which go) run volume_create.go
