language: go
sudo: required
dist: trusty
addons:
  apt:
    packages:
    # install cross compilers for cgo support.
    - gcc-aarch64-linux-gnu
    - libc6-dev-arm64-cross
    - libblkid-dev
before_install:
    - sudo apt-get update
    - sudo apt-get install gdisk
script:
    - git clone https://github.com/coreos/ignition
    - sudo ignition/build
    - sudo -E $(which go) run volume_create.go
